version: 2
jobs:
  build:
    macos:
      xcode: "9.0"
    steps:
      - checkout
      - run:
          name: Run script
          command: ./python.sh
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
